### ISSUE TITLE
Unable to connect to database since mysql upgrade

### ISSUE THREAD

**Issue by robwatkiss** [sensson/docker-magento2#9]
The ```mysql:latest``` image has recently been updated to version 8 and as a result the frontend container can no longer establish a database connection.

I would propose pinning the mysql image to version 5.7.23.

```yaml
services:
  mysql:
-    image: mysql:latest
+    image: mysql:5.7.23
    container_name: mysql
    restart: always
```
